In [3]:
import numpy as np

n1=np.array([1,2,3,4,5,6])
n1

In [20]:
n1=np.array([1,2,3,4,5,6])
n1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
n1.shape

(6,)

In [34]:
n1.ndim

1

In [46]:
n2=np.zeros((2,2,2))
n2

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [44]:
n2=np.ones((2,2,2))
n2

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [48]:
n2=np.full((2,2,),5)
n2

array([[5, 5],
       [5, 5]])

In [62]:
n3=np.arange(11,20).reshape(3,3)
n3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [64]:
n3=np.arange(11,20,5)
n3

array([11, 16])

In [70]:
n3=np.random.randint(10,20,5)
n3

array([18, 10, 10, 11, 13])

In [76]:
n3=np.random.randint(1,10,(5,5))
n3

array([[3, 6, 8, 9, 1],
       [8, 8, 7, 2, 6],
       [1, 5, 4, 1, 2],
       [3, 5, 8, 4, 9],
       [5, 7, 6, 7, 8]])

In [82]:
np.concatenate([n2,n2])

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [86]:
np.hstack([n2,n2])

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [88]:
np.vstack([n2,n2])

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [7]:
n1

NameError: name 'n1' is not defined

In [96]:
n2

array([[5, 5],
       [5, 5]])

In [98]:
n3

array([[3, 6, 8, 9, 1],
       [8, 8, 7, 2, 6],
       [1, 5, 4, 1, 2],
       [3, 5, 8, 4, 9],
       [5, 7, 6, 7, 8]])

In [15]:
import numpy as np
n1=np.array([1,2,3,4,5,6])
n1[3]

4

In [17]:
n3=np.arange(11,20).reshape(3,3)
n3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [19]:
n3[2,2]

19

In [21]:
n3[0,0]

11

In [27]:
#[start_row:end_row,start_column:end_column]
n3[1:2,0:1]

array([[14]])

In [33]:
n3[1:,0:]

array([[14, 15, 16],
       [17, 18, 19]])

In [35]:
np.save('my_nparray',n3)

In [37]:
np.load('my_nparray.npy')

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])